//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Color_Options
    {
        public int color_OptionsId { get; set; }
        [Required(ErrorMessage = "Please input the color Type !")] 
        public string color_Type { get; set; }
        [Required(ErrorMessage = "Please select Model!")] 
        public int productId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
