//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Supply
    {
        public Supply()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int suppyId { get; set; }
        [Required(ErrorMessage="please enter supplyname")]
        public string supplyname { get; set; }
         [Required(ErrorMessage = "please enter supplyname")]
        [Phone]
        public string telephone { get; set; }
        [Required(ErrorMessage = "please enter supplyname")]
        public string adress { get; set; }
       [Required(ErrorMessage = "please enter supplyname")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
